### ISSUE TITLE
Support `ember-cli-babel` v8

### ISSUE THREAD

**Issue by bertdeblock** [mainmatter/ember-test-selectors#1211]
Seeing this warning at the moment:

```
WARNING: ember-test-selectors: You are using an unsupported ember-cli-babel version. data-test properties are not automatically stripped from your JS code.
```

Though, it seems stripping `data-test` selectors does still work.

EDIT: We don't use `data-test` selectors in JS land, so that's why the results I'm seeing are still the same.

**Comment by bwbuchanan** [comment]
Could we get a release cut with this change please?

**Comment by bertdeblock** [comment]
Made https://github.com/mainmatter/ember-test-selectors/pull/1216 to get the ball rolling on a new release.
